from p2f_api.service.harm_data_types import create_harm_data_type
from p2f_pydantic.harm_data_types import HARM_Data_Type

unit_percentage = "percentage"
unit_celcius = "degrees Celcius"
unit_ppm = "parts per million"
unit_unknown = "unknown"
unit_meters = "meters"
unit_count = "count"


data_types = {
    "Aridity": {"units": unit_percentage, 
                "methods": ["insoluble dust", "calcium", "Nd/Sr provenance"],
                "is_proxy": True}, 
    "Sea ice extent": {"units": unit_percentage, 
                       "methods": ["bromine", "Na", "Water isotopes", "MSA", 
                                   "stable isotopes - organic matter", "biomarkers - IP25, PIP25",
                                   "biomarkers - IP25, PIP25", "biomarkers - IPSO25",
                                   "Forminifera assemblages", "Dinocyst assemblages",
                                   "Ancient DNA", "biomarkers: C37:4 alkenone",], 
                       "is_proxy": True},
    "Sea ice concentration": {"units": unit_percentage,
                              "methods": ["biomarkers - IP25, PIP25", "biomarkers - IPSO25",
                                          "Foraminifera assemblages", "Dinocyst assemblages",
                                          "Ancient DNA", "biomarkers - diet"],
                              "is_proxy": True},
    "Ice sheet/Ocean dynamics": {"units": unit_unknown,
                                 "methods": ["Ice rafted debris", "particle texture",
                                             "Sortable silt", "Natural gammaray",
                                             "XRF geochemistry", "Mineralogy/provenance",
                                             "Cosmogenic isotopes (10Be; 26Al)",
                                             "Radiogenic isotope (Sr/Nd)", 
                                             "Plant waxes", "Magnetic susceptibility",
                                             "Radiocarbon", "GDGTs",
                                             "Isotope tracers ( δ18O, 187Os/188Os)"],
                                 "is_proxy": True},
    "Surface ocean temperature": {"units": unit_celcius,
                                  "methods": ["Microfossil assemblages", "UK37",
                                              "TEX86", "Planktonic foraminifera Mg/Ca",
                                              "clumped isotopes planktic forams", 
                                              "Long-chain diols"],
                                  "is_proxy": True},
    "Deep ocean temperature": {"units": unit_celcius,
                               "methods": ["clumped isotopes benthic forams", 
                                           "Benthic foraminifera Mg/Ca"],
                               "is_proxy": True},
    "Deep ocean chemistry": {"units": unit_unknown,
                             "methods": ["trace metals benthic forams", 
                                         "stable isotopes"],
                             "is_proxy": True},
    "Deep ocean ventillation": {"units": unit_unknown,
                                "methods": ["stable isotopes"],
                                "is_proxy": True},
    "Surface ocean salinity": {"units": unit_percentage,
                               "methods": ["Planktonic foraminifera geochemistry", 
                                           "alkenone dD", "biomarkers - C37:4 alkenone"],
                               "is_proxy": True},
    "ice volume / sea level": {"units": unit_meters,
                               "methods": ["Oxygen isotopic composition of ancient seawater", 
                                           "Benthic foraminifera Mg/Ca"],
                               "is_proxy": True},
    "ocean circulation": {"units": unit_unknown,
                          "methods": ["Nd isotopes", "Sortable silt",
                                      "benthic foram- carbon isotopes", 
                                      "d18O forams coupled with temperature"],
                          "is_proxy": True},
    "Atmospheric CO2": {"units": unit_ppm,
                        "methods": ["planktonic foram Boron isotopes"],
                        "is_proxy": True},
    "Terrestrial climate": {"units": unit_unknown,
                            "methods": ["Pollen", "Leaf waxes", "GDGTs",
                                        "Oxygen isotopes", "Elemental analysis", 
                                        "Magnetic susceptibility",
                                        "charcoal"],
                            "is_proxy": True},
    "Terrestrial temperature": {"units": unit_celcius,
                                "methods": ["Tree ring width", "d18O",
                                            "MXD"],
                                "is_proxy": True},
    "Summer sunshine & cloud cover": {"units": unit_percentage,
                                      "methods": ["d13C", "Blue light intensity"],
                                      "is_proxy": True},
    "Humidty": {"units": unit_percentage,
                "methods": ["d18O"],
                "is_proxy": True},
    "Atmospheric carbon cycle": {"units": unit_unknown,
                                 "methods": ["d13C", "Radiocarbon istopes"],
                                 "is_proxy": True},     
    "Surface temperature": {"units": unit_celcius,
                            "methods": ["Delta 18O", "15N", "borehole temperature"],
                            "is_proxy": True},   
    "Atmospheric gases": {"units": unit_ppm,
                          "methods": ["CO2 direct measurement", "CH4 direct", 
                                      "N2O", "boron isotopes - foram"],
                          "is_proxy": True},   
    "mean ocean temperature": {"units": unit_celcius,
                               "methods": ["noble gas ratios"],
                               "is_proxy": True},   
    "Ice sheet altitude": {"units": unit_meters,
                           "methods": ["d18O", "Total air content"],
                           "is_proxy": True},   
    "Accumulation": {"units": unit_unknown,
                     "methods": ["chemistry seasonal+thinning model", "d18O+thinning model"],
                     "is_proxy": True},   
    "Forest fires": {"units": unit_count,
                     "methods": ["NH4"],
                     "is_proxy": True},                      
}

for datatype in data_types.keys():
    # In the future add calibration handling here
    for method in data_types[datatype]["methods"]: 
        create_harm_data_type(HARM_Data_Type(measure=datatype,
                                             unit_of_measurement=data_types[datatype]["units"],
                                             method=method, 
                                             is_proxy=data_types[datatype]["is_proxy"]))