# Local libraries
from p2f_api.apilogs import logger, fa
from ..service import link_git
from .temp_accounts import combined_auth, api_token_annotation
from p2f_pydantic.link_git import Git_Repository
from p2f_pydantic.temp_accounts import Temp_Account

# Third Party Libraries
from fastapi import Body, APIRouter, Depends

# Batteries included libraries
import uuid
from typing import Optional, List, Annotated
from inspect import stack

tag_name = "Git"

router = APIRouter(prefix="/git", tags=[tag_name])

tag_metadata = {"name": tag_name,
                "description": 
                """In addition to HARM References, you might want to associate a Git repository with a dataset.

Git repositories have the following attributes:

* git_repo_id : A unique identifier for each git repository, this is generated by the API and does not reference anything within an actual git repository. Do not generate this yourself.
* git_repo_url : The url for the git repository, This should end with .git, but that is not enforced. 
* is_p2f_repo : A boolean flag for if a git repository has been created by members of the Past 2 Future project. """}

# List
@router.get("/", operation_id="git-list")
def list_git_repositories(
    auth: api_token_annotation,
    dataset_id: Optional[uuid.UUID] = None,
) -> List[Git_Repository]:
    logger.debug(f"{fa.web}{fa.list} {__name__} {stack()[0][3]}()")
    return link_git.list_git(dataset_id=dataset_id)


# Get Single
@router.get("/{git_repo_id}", operation_id="git-get")
def get_git_repo(auth: api_token_annotation,
                 git_repo_id: Optional[uuid.UUID] = None) -> Git_Repository:
    logger.debug(f"{fa.web}{fa.get} {__name__} {stack()[0][3]}()")
    return link_git.get_git(git_repo_id=git_repo_id)


# Create
@router.post("/", operation_id="git-create")
def create_git_repo(
    auth: api_token_annotation,
    new_git_repo: Git_Repository, dataset_id: Optional[uuid.UUID] = None
) -> Git_Repository:
    logger.debug(f"{fa.web}{fa.create} {__name__} {stack()[0][3]}()")
    return link_git.create_git_repo(new_git_repo, dataset_id)


# Delete
@router.delete("/{git_repo_id}", include_in_schema=False, operation_id="git-delete")
def delete_git_repo(auth: api_token_annotation,
                    git_repo_id: Optional[uuid.UUID] = None) -> None:
    logger.debug(f"{fa.web}{fa.delete} {__name__} {stack()[0][3]}()")
    return link_git.delete_git_repo(git_repo_id)


# Assign
@router.post("/assign", operation_id="git_dataset-assign")
def assign_git_repo(auth: api_token_annotation,
                    git_repo_id: uuid.UUID, dataset_id: uuid.UUID):
    logger.debug(f"{fa.web}{fa.assign} {__name__} {stack()[0][3]}()")
    return link_git.assign_git_repo(git_repo_id, dataset_id)


# Remove
@router.delete("/remove", operation_id="git_dataset-remove")
def unlink_git_repo(auth: api_token_annotation,
                    git_repo_id: uuid.UUID, dataset_id: uuid.UUID):
    logger.debug(f"{fa.web}{fa.delete} {__name__} {stack()[0][3]}()")
    return link_git.unlink_git_repo(git_repo_id, dataset_id)
