apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: p2f-api
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: harica
    ingress.citrix.com/insecure-termination: redirect
spec:
  ingressClassName: nsic-vpx
  rules:
  - host: {hostname}
    http:
      paths:
      - backend:
          service:
            name: p2f-api
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {hostname}
    secretName: p2f-api-tls
--- 
apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
  name: httpxforwardedforadd
spec:
  rewrite-policies:
    - servicenames:
        - p2f-api
      rewrite-policy:
        operation: insert_http_header
        target: X-Forwarded-For
        modify-expression: client.ip.src
        comment: 'HTTP Initial X-Forwarded-For header add'
        direction: REQUEST
        rewrite-criteria: 'HTTP.REQ.HEADER("X-Forwarded-For").EXISTS.NOT'

    - servicenames:
        - p2f-api
      rewrite-policy:
        operation: replace
        target: HTTP.REQ.HEADER("X-Forwarded-For")
        modify-expression: 'HTTP.REQ.HEADER("X-Forwarded-For").APPEND(",").APPEND(CLIENT.IP.SRC)'
        comment: 'HTTP Append X-Forwarded-For IPs'
        direction: REQUEST
        rewrite-criteria: 'HTTP.REQ.HEADER("X-Forwarded-For").EXISTS'